# Generated by Django 4.2.15 on 2024-09-05 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='is_occupied',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='number',
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
        ),
    ]
