# Generated by Django 4.2.15 on 2024-09-14 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0003_table_description_table_name_alter_category_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='description',
        ),
        migrations.RemoveField(
            model_name='table',
            name='name',
        ),
    ]
