# Generated by Django 4.2.15 on 2024-12-03 09:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0006_weekday_weeklycalendar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weeklycalendar',
            name='menu_item',
        ),
        migrations.AlterField(
            model_name='weekday',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='weekday',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='weeklycalendar',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
